apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - image: mmoustafa/reverseproxy:latest
    name: reverseproxy
    imagePullPolicy: Always          
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"       
    ports:
    - containerPort: 8080
  restartPolicy: Always